<!DOCTYPE html>
<html>
    <head>
        <meta charset=utf-8>
        <base href="<?php echo $base_url;?>" />
        <link type="text/css" rel="stylesheet" href="<?php echo str_replace('../','',XPCMS_PAGE_PATH).'css/';?>base.css"/>
        <link type="text/css" rel="stylesheet" href="<?php echo str_replace('../','',XPCMS_PAGE_PATH).'css/';?>layout.css"/>
        <link type="text/css" rel="stylesheet" href="<?php echo str_replace('../','',XPCMS_PAGE_PATH).'css/';?>content.css"/>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    </head>
    <body>
        <div id="wrap">
		